name: Check for Linked Issue

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if PR is linked to an issue
      uses: actions/github-script@v6
      with:
        script: |
          const linkedIssues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'all',
            labels: `linked:pr-${context.payload.pull_request.number}`
          });

          if (linkedIssues.data.length === 0) {
            core.setFailed('This pull request does not have a linked issue.');
          }
